from enum import Enum

class ReviewType(str, Enum):
    EQUIPMENT = "EQUIPMENT"
    MARKETPLACE_PRODUCT = "MARKETPLACE_PRODUCT"
    SPRAYER_SERVICE = "SPRAYER_SERVICE"
    SELLER = "SELLER"
    EQUIPMENT_OWNER = "EQUIPMENT_OWNER"
    SPRAYER_OPERATOR = "SPRAYER_OPERATOR"

class ModerationStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    HIDDEN = "HIDDEN"
    REPORTED = "REPORTED"
    SPAM = "SPAM"

class TargetRole(str, Enum):
    SELLER = "SELLER"
    FARMER = "FARMER"
    EQUIPMENT_OWNER = "EQUIPMENT_OWNER"
    SPRAYER_OPERATOR = "SPRAYER_OPERATOR"
    SYSTEM = "SYSTEM"
