# ==========================================
# KisanO - Centralized Error Code Registry
# ==========================================
from enum import Enum

class ErrorCode(str, Enum):
    # Authentication & Authorization
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED"
    AUTH_ACCOUNT_SUSPENDED = "AUTH_ACCOUNT_SUSPENDED"
    AUTH_DUPLICATE_EMAIL = "AUTH_DUPLICATE_EMAIL"
    AUTH_DUPLICATE_PHONE = "AUTH_DUPLICATE_PHONE"
    AUTH_INVALID_OTP = "AUTH_INVALID_OTP"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_TOO_MANY_REQUESTS = "AUTH_TOO_MANY_REQUESTS"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_SESSION_INVALID = "AUTH_SESSION_INVALID"

    # Validation & System
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # Payments
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"

    # Entities
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    BOOKING_INVALID_STATE = "BOOKING_INVALID_STATE"
    EQUIPMENT_NOT_FOUND = "EQUIPMENT_NOT_FOUND"
    EQUIPMENT_UNAVAILABLE = "EQUIPMENT_UNAVAILABLE"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"

    # External Services
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    SMS_SERVICE_UNAVAILABLE = "SMS_SERVICE_UNAVAILABLE"
