import { ROLES, Role } from './roles';
import { PERMISSIONS, Permission } from './permissions';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_VERIFICATIONS,
    PERMISSIONS.MANAGE_MARKETPLACE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_LOGS,
    // Admins usually have access to everything
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.VIEW_PAYMENT,
  ],
  [ROLES.FARMER]: [
    PERMISSIONS.FARMER_DASHBOARD,
    PERMISSIONS.RENT_EQUIPMENT,
    PERMISSIONS.HIRE_SPRAYER,
    PERMISSIONS.PURCHASE_SUPPLIES,
    PERMISSIONS.AI_DOCTOR,
    PERMISSIONS.AI_RECOMMENDATION,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.CREATE_PAYMENT,
    PERMISSIONS.VIEW_PAYMENT,
  ],
  [ROLES.EQUIPMENT_OWNER]: [
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_UPDATE,
    PERMISSIONS.EQUIPMENT_DELETE,
    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_UPDATE, // Accept/Reject bookings
    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.VIEW_PAYMENT,
  ],
  [ROLES.SPRAYER]: [
    PERMISSIONS.SPRAYER_DASHBOARD,
    PERMISSIONS.MANAGE_SPRAY_SERVICES,
    PERMISSIONS.ACCEPT_SPRAY_JOB,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.VIEW_WALLET,
    PERMISSIONS.VIEW_PAYMENT,
  ],
  [ROLES.OPERATOR]: [
    // Operator is likely a specialized role for equipment operators
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.VIEW_PAYMENT,
  ],
};
